db:
  type: mongodb
  host: 192.168.10.99
  port: 27017
  database: cursuri-iso
  poolSize: 5
mq:
  host: 192.168.10.99
  port: 5672
  username: rabbitmq
  password: rabbitmq
  retryCount: 10
  retryTimeout: 5